"""Competition record metadata for the CCGC C5 text format."""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from typing import Sequence

from game.notation import MoveRecord
from records.parser import parse_record


@dataclass(frozen=True)
class RecordMetadata:
    game_type: str = "C5"
    black_team: str = ""
    white_team: str = ""
    result: str = ""
    datetime_location: str = ""
    event_name: str = ""
    raw_items: tuple[str, ...] = ()

    def header_items(self) -> list[str]:
        items = [
            self.game_type,
            self.black_team,
            self.white_team,
            self.result,
            self.datetime_location,
            self.event_name,
        ]
        return [item for item in items if item]


@dataclass(frozen=True)
class ParsedRecord:
    metadata: RecordMetadata
    moves: list[MoveRecord]


def _strip_outer_braces(record_text: str) -> str:
    text = str(record_text).strip()
    while text.startswith("{") and text.endswith("}") and len(text) >= 2:
        text = text[1:-1].strip()
    return text


def _header_text(record_text: str) -> str:
    inner = _strip_outer_braces(record_text)
    return inner.split(";", 1)[0].strip()


def _metadata_from_items(items: Sequence[str]) -> RecordMetadata:
    cleaned = tuple(str(item).strip() for item in items if str(item).strip())
    values = list(cleaned) + [""] * max(0, 6 - len(cleaned))
    return RecordMetadata(
        game_type=values[0] or "C5",
        black_team=values[1],
        white_team=values[2],
        result=values[3],
        datetime_location=values[4],
        event_name=values[5],
        raw_items=cleaned,
    )


def parse_record_metadata(record_text: str) -> RecordMetadata:
    """Parse the standard header before the first semicolon.

    Standard examples use bracketed header items:
    ``{[C5][先手参赛队 B][后手参赛队 W][先手胜]...;B(J,10)}``.
    Legacy ``{C5;...}`` records are accepted and return only ``game_type``.
    """
    header = _header_text(record_text)
    bracket_items = re.findall(r"\[([^\]]*)\]", header)
    if bracket_items:
        return _metadata_from_items(bracket_items)
    if header:
        return _metadata_from_items([header])
    return RecordMetadata(raw_items=())


def parse_standard_record(record_text: str) -> ParsedRecord:
    """Parse metadata and moves, enforcing standard MARK[-2..2] values."""
    metadata = parse_record_metadata(record_text)
    moves = parse_record(record_text, strict_mark=True)
    return ParsedRecord(metadata=metadata, moves=moves)


def build_record_filename(metadata: RecordMetadata) -> str:
    """Build the CCGC-style text filename for a record."""
    parts = [
        metadata.game_type or "C5",
        f"{metadata.black_team} vs {metadata.white_team}".strip(),
        metadata.result,
        metadata.datetime_location,
        metadata.event_name,
    ]
    safe_parts = [_sanitize_filename_part(part) for part in parts if part and part.strip()]
    return "-".join(safe_parts) + ".txt"


def _sanitize_filename_part(part: str) -> str:
    text = str(part).replace(":", "：")
    return re.sub(r'[<>"/\\|?*]+', "_", text).strip()


def parse_record_filename(filename: str) -> RecordMetadata:
    """Parse a CCGC-style filename generated by ``build_record_filename``."""
    stem = os.path.splitext(os.path.basename(filename))[0]
    parts = stem.split("-")
    game_type = parts[0] if len(parts) > 0 else "C5"
    black_team = ""
    white_team = ""
    if len(parts) > 1 and " vs " in parts[1]:
        black_team, white_team = parts[1].split(" vs ", 1)
    result = parts[2] if len(parts) > 2 else ""
    datetime_location = parts[3].replace("：", ":") if len(parts) > 3 else ""
    event_name = "-".join(parts[4:]) if len(parts) > 4 else ""
    return RecordMetadata(
        game_type=game_type,
        black_team=black_team,
        white_team=white_team,
        result=result,
        datetime_location=datetime_location,
        event_name=event_name,
        raw_items=tuple(part for part in parts if part),
    )


__all__ = [
    "ParsedRecord",
    "RecordMetadata",
    "build_record_filename",
    "parse_record_filename",
    "parse_record_metadata",
    "parse_standard_record",
]
